language: cpp
sudo: required
dist: xenial
compiler:
- gcc

branches:
  only:
  - master

before_script:
 - sudo apt-get -qq update
 - sudo apt-get install -y libgtest-dev cmake
 - sudo apt-get install -y linux-tools-common linux-tools-generic linux-tools-`uname -r`
 - sudo wget https://github.com/google/googletest/archive/release-1.7.0.tar.gz
 - sudo tar xf release-1.7.0.tar.gz
 - pushd googletest-release-1.7.0
 - sudo cmake -DBUILD_SHARED_LIBS=ON .
 - sudo make
 - sudo cp -a include/gtest /usr/include
 - sudo cp -a libgtest_main.so libgtest.so /usr/lib/
 - sudo sh -c 'echo 1 > /proc/sys/kernel/perf_event_paranoid'
 - sudo perf list
 - sudo perf stat -e mem-loads ls
 - popd

script:
  - ./build.sh
  - ./install.sh
  - ./demo/demo.sh -p

after_success:
  - PATH=./install/runtime/bin:${PATH} python -m pip install codecov
  - PATH=./install/runtime/bin:${PATH} codecov
